import jenkins.model.Jenkins
import hudson.triggers.SCMTrigger
import org.jenkinsci.plugins.workflow.job.WorkflowJob
import org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition
import org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty

String jobName = 'e102-dev-deploy'
File marker = new File('/var/jenkins_home/.e102-dev-deploy-job-created')
String pipelineScript = new String('cGlwZWxpbmUgewogIGFnZW50IGFueQoKICBvcHRpb25zIHsKICAgIGRpc2FibGVDb25jdXJyZW50QnVpbGRzKCkKICB9CgogIGVudmlyb25tZW50IHsKICAgIFJFUE9fVVJMID0gJ2h0dHBzOi8vbGFiLnNzYWZ5LmNvbS9zMTQtZmluYWwvUzE0UDMxRTEwMi5naXQnCiAgfQoKICBzdGFnZXMgewogICAgc3RhZ2UoJ0NoZWNrb3V0JykgewogICAgICBzdGVwcyB7CiAgICAgICAgZ2l0IGJyYW5jaDogJ2RldmVsb3AnLCBjcmVkZW50aWFsc0lkOiAnZ2l0bGFiLXBhdCcsIHVybDogZW52LlJFUE9fVVJMCiAgICAgIH0KICAgIH0KCiAgICBzdGFnZSgnUHJlcGFyZSBTZXJ2ZXIgQ29uZmlnJykgewogICAgICBzdGVwcyB7CiAgICAgICAgd2l0aENyZWRlbnRpYWxzKFtmaWxlKGNyZWRlbnRpYWxzSWQ6ICdlMTAyLWRldi1lbnYtZmlsZScsIHZhcmlhYmxlOiAnRTEwMl9ERVZfRU5WJyldKSB7CiAgICAgICAgICBzaCAnJycKICAgICAgICAgICAgY3AgIiRFMTAyX0RFVl9FTlYiIC5lbnYuZGV2CiAgICAgICAgICAgIGNwIC9vcHQvZTEwMi1zZXJ2ZXIvZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIGRvY2tlci1jb21wb3NlLnMxLm92ZXJyaWRlLnltbAogICAgICAgICAgICBjaG1vZCA2MDAgLmVudi5kZXYKICAgICAgICAgICcnJwogICAgICAgIH0KICAgICAgfQogICAgfQoKICAgIHN0YWdlKCdDb21wb3NlIENvbmZpZycpIHsKICAgICAgc3RlcHMgewogICAgICAgIHNoICdkb2NrZXIgY29tcG9zZSAtLWVudi1maWxlIC5lbnYuZGV2IC1mIGRvY2tlci1jb21wb3NlLmRldi55bWwgLWYgZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIC0tcHJvZmlsZSBncmFwaGhvcHBlci1idWlsZCBjb25maWcgLS1xdWlldCcKICAgICAgfQogICAgfQoKICAgIHN0YWdlKCdJbmZyYSBVcCcpIHsKICAgICAgc3RlcHMgewogICAgICAgIHNoICdkb2NrZXIgY29tcG9zZSAtLWVudi1maWxlIC5lbnYuZGV2IC1mIGRvY2tlci1jb21wb3NlLmRldi55bWwgLWYgZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIHVwIC1kIHBvc3RncmVzIHJlZGlzIG1pbmlvIG1pbmlvLWluaXQgYWknCiAgICAgIH0KICAgIH0KCiAgICBzdGFnZSgnR3JhcGhIb3BwZXIgQ2FjaGUnKSB7CiAgICAgIHN0ZXBzIHsKICAgICAgICBzaCAnJycKICAgICAgICAgIHNldCAtZXUKICAgICAgICAgIGlmIGRvY2tlciB2b2x1bWUgaW5zcGVjdCBzMTRwMzFlMTAyLWRldl9ncmFwaGhvcHBlci1kZXYtZGF0YSA+L2Rldi9udWxsIDI+JjEgXAogICAgICAgICAgICAmJiBkb2NrZXIgcnVuIC0tcm0gLXYgczE0cDMxZTEwMi1kZXZfZ3JhcGhob3BwZXItZGV2LWRhdGE6L2dyYXBoaG9wcGVyL2RhdGEgYWxwaW5lOjMuMjAgc2ggLWMgJ3Rlc3QgLW4gIiQoZmluZCAvZ3JhcGhob3BwZXIvZGF0YSAtbWluZGVwdGggMSAtbWF4ZGVwdGggMSAyPi9kZXYvbnVsbCkiJzsgdGhlbgogICAgICAgICAgICBlY2hvICJHcmFwaEhvcHBlciBncmFwaC1jYWNoZSBhbHJlYWR5IGV4aXN0cy4gU2tpcHBpbmcgYnVpbGQuIgogICAgICAgICAgZWxzZQogICAgICAgICAgICBkb2NrZXIgY29tcG9zZSAtLWVudi1maWxlIC5lbnYuZGV2IC1mIGRvY2tlci1jb21wb3NlLmRldi55bWwgLWYgZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIC0tcHJvZmlsZSBncmFwaGhvcHBlci1idWlsZCBidWlsZCBncmFwaGhvcHBlci1idWlsZAogICAgICAgICAgICBkb2NrZXIgY29tcG9zZSAtLWVudi1maWxlIC5lbnYuZGV2IC1mIGRvY2tlci1jb21wb3NlLmRldi55bWwgLWYgZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIC0tcHJvZmlsZSBncmFwaGhvcHBlci1idWlsZCBydW4gLS1ybSBncmFwaGhvcHBlci1idWlsZAogICAgICAgICAgZmkKICAgICAgICAgIGRvY2tlciBjb21wb3NlIC0tZW52LWZpbGUgLmVudi5kZXYgLWYgZG9ja2VyLWNvbXBvc2UuZGV2LnltbCAtZiBkb2NrZXItY29tcG9zZS5zMS5vdmVycmlkZS55bWwgdXAgLWQgZ3JhcGhob3BwZXIKICAgICAgICAnJycKICAgICAgfQogICAgfQoKICAgIHN0YWdlKCdCYWNrZW5kIERlcGxveScpIHsKICAgICAgc3RlcHMgewogICAgICAgIHNoICdkb2NrZXIgY29tcG9zZSAtLWVudi1maWxlIC5lbnYuZGV2IC1mIGRvY2tlci1jb21wb3NlLmRldi55bWwgLWYgZG9ja2VyLWNvbXBvc2UuczEub3ZlcnJpZGUueW1sIHVwIC1kIC0tYnVpbGQgLS1uby1kZXBzIGJhY2tlbmQnCiAgICAgIH0KICAgIH0KCiAgICBzdGFnZSgnU21va2UgVGVzdCcpIHsKICAgICAgc3RlcHMgewogICAgICAgIHNoICcnJwogICAgICAgICAgZm9yIGkgaW4gJChzZXEgMSAyNCk7IGRvCiAgICAgICAgICAgIGRvY2tlciBydW4gLS1ybSAtLW5ldHdvcmsgczE0cDMxZTEwMi1kZXZfZGVmYXVsdCBjdXJsaW1hZ2VzL2N1cmw6bGF0ZXN0IC1mc1MgaHR0cDovL2JhY2tlbmQ6ODA4MC92My9hcGktZG9jcyA+L3RtcC9lMTAyLWFwaS1kb2NzLmpzb24gXAogICAgICAgICAgICAgICYmIGRvY2tlciBydW4gLS1ybSAtLW5ldHdvcmsgczE0cDMxZTEwMi1kZXZfZGVmYXVsdCBjdXJsaW1hZ2VzL2N1cmw6bGF0ZXN0IC1mc1MgaHR0cDovL2dyYXBoaG9wcGVyOjg5OTAvaGVhbHRoY2hlY2sgPi90bXAvZTEwMi1ncmFwaGhvcHBlci1oZWFsdGgudHh0IFwKICAgICAgICAgICAgICAmJiBleGl0IDAKICAgICAgICAgICAgc2xlZXAgNQogICAgICAgICAgZG9uZQogICAgICAgICAgZG9ja2VyIGNvbXBvc2UgLS1lbnYtZmlsZSAuZW52LmRldiAtZiBkb2NrZXItY29tcG9zZS5kZXYueW1sIC1mIGRvY2tlci1jb21wb3NlLnMxLm92ZXJyaWRlLnltbCBsb2dzIC0tdGFpbD0xMjAgYmFja2VuZCBncmFwaGhvcHBlcgogICAgICAgICAgZXhpdCAxCiAgICAgICAgJycKICAgICAgfQogICAgfQoKICAgIHN0YWdlKCdTdGF0dXMnKSB7CiAgICAgIHN0ZXBzIHsKICAgICAgICBzaCAnZG9ja2VyIGNvbXBvc2UgLS1lbnYtZmlsZSAuZW52LmRldiAtZiBkb2NrZXItY29tcG9zZS5kZXYueW1sIC1mIGRvY2tlci1jb21wb3NlLnMxLm92ZXJyaWRlLnltbCBwcycKICAgICAgfQogICAgfQogIH0KfQo='.decodeBase64(), 'UTF-8')

Jenkins j = Jenkins.get()
def job = j.getItem(jobName)
if (job == null) {
  job = j.createProject(WorkflowJob.class, jobName)
}
job.setDescription('Deploy develop branch to S1 dev Docker Compose stack. GraphHopper cache is built from PostgreSQL LineString when missing.')
job.setDefinition(new CpsFlowDefinition(pipelineScript, true))
if (job.getProperty(PipelineTriggersJobProperty.class) == null) {
  job.addProperty(new PipelineTriggersJobProperty([new SCMTrigger('H/30 * * * *')]))
}
job.save()

if (!marker.exists()) {
  job.scheduleBuild2(0)
  marker.text = new Date().toString()
  println("${jobName} configured and initial build scheduled")
} else {
  println("${jobName} configured")
}
