CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS bus_stops (
    bus_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bstop_id VARCHAR(30) NOT NULL,
    stop_name VARCHAR(100) NOT NULL,
    ars_no VARCHAR(20),
    stop_type VARCHAR(30),
    point geometry(Point, 4326) NOT NULL,
    active BOOLEAN NOT NULL,
    synced_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_bus_stops_bstop_id ON bus_stops (bstop_id);
CREATE INDEX IF NOT EXISTS idx_bus_stops_active ON bus_stops (active);
CREATE INDEX IF NOT EXISTS idx_bus_stops_stop_name ON bus_stops (stop_name);
CREATE INDEX IF NOT EXISTS idx_bus_stops_ars_no ON bus_stops (ars_no);

CREATE TABLE IF NOT EXISTS subway_station_accessibility_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subway_station_id BIGINT NOT NULL,
    feature_type VARCHAR(50) NOT NULL,
    is_available BOOLEAN NOT NULL,
    CONSTRAINT fk_subway_station_accessibility_features_station
        FOREIGN KEY (subway_station_id)
        REFERENCES subway_stations (subway_station_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_subway_station_accessibility_features_station_type
    ON subway_station_accessibility_features (subway_station_id, feature_type);
CREATE INDEX IF NOT EXISTS idx_subway_station_accessibility_features_station
    ON subway_station_accessibility_features (subway_station_id);

ALTER TABLE IF EXISTS bookmarks
    ALTER COLUMN place_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    log_id BIGSERIAL PRIMARY KEY,
    actor_user_id UUID,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(120),
    gu VARCHAR(40),
    dong VARCHAR(80),
    summary TEXT NOT NULL,
    before_json JSONB,
    after_json JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_log_id
    ON admin_audit_logs (log_id DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_filter
    ON admin_audit_logs (action, gu, dong, actor_user_id, log_id DESC);

CREATE TABLE IF NOT EXISTS routing_segment_overrides (
    edge_id BIGINT PRIMARY KEY,
    walk_access VARCHAR(30) NOT NULL,
    CONSTRAINT fk_routing_segment_overrides_edge_id
        FOREIGN KEY (edge_id)
        REFERENCES road_segments (edge_id)
        ON DELETE CASCADE
);
