CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS bus_stops (
    bus_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bstop_id VARCHAR(30) NOT NULL,
    stop_name VARCHAR(100) NOT NULL,
    ars_no VARCHAR(20),
    stop_type VARCHAR(30),
    point geometry(Point, 4326) NOT NULL,
    active BOOLEAN NOT NULL,
    synced_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_bus_stops_bstop_id ON bus_stops (bstop_id);
CREATE INDEX IF NOT EXISTS idx_bus_stops_active ON bus_stops (active);
CREATE INDEX IF NOT EXISTS idx_bus_stops_stop_name ON bus_stops (stop_name);
CREATE INDEX IF NOT EXISTS idx_bus_stops_ars_no ON bus_stops (ars_no);

ALTER TABLE IF EXISTS bookmarks
    ALTER COLUMN place_id DROP NOT NULL;
