graphhopper:
  datareader.file: ""
  graph.location: graph-cache

  profiles:
    - name: foot

  profiles_ch: []
  profiles_lm: []

  prepare.min_network_size: 2
  prepare.subnetworks.threads: 1
  routing.non_ch.max_waypoint_distance: 1000000
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
  request_log:
    appenders: []

logging:
  appenders:
    - type: console
